version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    networks:
      - oj-network

  compiler-backend:
    build:
      context: ./Online-compiler
    container_name: compiler-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    networks:
      - oj-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    networks:
      - oj-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - oj-network

networks:
  oj-network:
    driver: bridge
